# NOW TV Help Site
#
# For more information visit: https://circleci.com/docs/configuration/
version: 2
jobs:
  build:
    steps:
      - checkout
    - run:
          name: Deploy DF Communities
          shell: ../config/scripts/ci.sh
