version: 2
jobs:
  build:
    docker:
      - image: java:openjdk7
    steps:
      - checkout
      - run: ./config/scripts/ci.sh
      - run:
          name: Print the Current Time
          command: date
