version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install dependancy 
          command: sudo yum install ant
      - run:
          name: DF Deployment
          command: ./config/scripts/ci.sh
      - run:
          name: Print the Current Time
          command: date
