# NOW TV Help Site
#
# For more information visit: https://circleci.com/docs/configuration/
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
    - run:
          name: Deploy DF Communities
          command: ../config/scripts/ci.sh
