version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install dependancy 
          shell: /bin/sh
          command: echo $0
      - run:
          name: DF Deployment
          command: ./config/scripts/ci.sh
      - run:
          name: Print the Current Time
          command: date
