@isTest
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Test Class for WEBC_VerifyRegistration_Controller
 *  Author  : Lakshmi Rajendram
 *  Date    : 23-02-2015
 *  Version : 0.1 Unit Test
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/

public with sharing class WEBC_VerifyRegistration_Ctlr_Test {


    
    static testMethod void doTest() {
    
     
    
    // See DF_WEBC_VerifyRegistration_Controller_Test


      }

}