/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBRegisterChampion.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the WEBRegisterChampion page.
 *					This will be used when people wish to register as a Champion
 *					Contains a call out to the reCaptcha security application
 *					And the standard Site login code
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public with sharing class WEBRegisterChampion extends WEBController {

}